# Generated by Django 5.2.7 on 2025-10-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(),
        ),
    ]
