# Generated by Django 5.2.7 on 2025-10-08 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_fecha_fin_alter_reserva_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion'),
        ),
    ]
